### ISSUE TITLE
SSI includes are vulnerable to XSS

### ISSUE THREAD

**Issue by Jzwhh** [Cognifide/Sling-Dynamic-Include#11]
How to reproduce:

- Enable SSI Include for the resourceType of a non-synthetic resource
- Open the page that contains the resource with the following suffix:

-->\<script>alert('XSS')\</script>\<script>alert('XSS')\</script>" in *url* before appending it to *buf*

**Comment by trekawek** [comment]
Thanks for finding this. I was able to reproduce the bug and will release the fixed version in 24h.

**Comment by trekawek** [comment]
Issue has been fixed in the version 2.0.3.

**Comment by Jzwhh** [comment]
Thank you!

**Comment by Jzwhh** [comment]
We sadly encountered a problem with this fix in our project: We use the '=' character in the selector of one of our components. '=' gets removed by the new .sanitize()-Method. Could you please make the sanitize-Regex configurable via the OSGi config or allow the '='-Character?

**Comment by trekawek** [comment]
I [committed](https://github.com/Cognifide/Sling-Dynamic-Include/commit/c0061ea1eccd0bc27ae4902d0d4107b43551f291) the second option. Could you check if the current SNAPSHOT works for you? If it does, I'll make a release.

**Comment by Jzwhh** [comment]
yes, commit c0061ea1ec will fix our problem. Thank you.

**Comment by trekawek** [comment]
Thanks, the fixed version 2.0.4 has been released.
