### ISSUE TITLE
ignoreUrlParams dispatcher configuration breaks rendering of virtual includes

### ISSUE THREAD

**Issue by elysian** [Cognifide/Sling-Dynamic-Include#12]
Dispatcher module supports the definition of ignoreUrlParams, a list of query parameters that should not bypass the caching mechanism with the result being laid into the web servers cache directories. Our main use case for this is to be able to cache readily rendered responses, when certain query parameters exist, i.e for incoming URL's containing tracking links as it happens for Adobe Analytics with all "utm_*" parameters.

The dispatcher module itself then puts the rendered response into the web server cache, as supposed to. Unfortunately, IncludeTagWritingProcessor generally ignores all requests, regardless of which parameters are contained in the query string. Therefore, such requests bypass the SDI feature at all, leading to the situation where SDI-configured components are not rendered with the proper include directive.

The best solution would be to have a configurable String[] on IncludeTagWritingProcessor to be able to define the ignoreUrlParams. These should be checked against in its accepts() method to allow rendering include directives in such scenarios as well, instead of plainly rejecting all URL's containing more than zero parameters:
Enumeration<?> params = request.getParameterNames();
if (params.hasMoreElements()) {
  // add check against configured list of allowed parameters (=ignoreUrlParams in dispatcher config)
  return false;
}

**Comment by trekawek** [comment]
Done in the experimental branch develop-2.1.0.
