### ISSUE TITLE
Support for more characters in selectors

### ISSUE THREAD

**Issue by L3444** [Cognifide/Sling-Dynamic-Include#13]
We SSI-include a component with a selector that sometimes contains special characters.

Example:

Correct URL: /content/site1/en_GB/product/_jcr_content/main/product/par/productinfo.productId=45$190-7547.html

SDI renders: 

The special characters in productId get removed which means we can't find the product in the JCR

For us, allowing the following characters would be sufficient, but I'm sure that there are other projects were different special characters would be needed: !$'()+,-<>~_`äöüÄÖÜß

Could you please put the allowed characters into an OSGi-config or remove this restriction altogether?

Secondly, the rendering of the SSI-Include lacks proper escaping. From what I've gathered from http://httpd.apache.org/docs/2.2/howto/ssi.html, at least the characters " and $ have to be escaped by putting a "\" before them.

**Comment by stawniak** [comment]
I'll do it. It will support special characters, as long as the URL is valid according to the spec.

**Comment by stawniak** [comment]
Ok, done. I've done proper escaping instead of removing unusual characters.

**Comment by L3444** [comment]
The new release crashes with the following exception and afterwards renders the component html normally instead of rendering the include:

java.net.URISyntaxException: Illegal character in path at index 39: http://example.de/test.productid=abc123<456.html
	at java.net.URI$Parser.fail(Unknown Source)
	at java.net.URI$Parser.checkChars(Unknown Source)
	at java.net.URI$Parser.parseHierarchical(Unknown Source)
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
        at com.cognifide.cq.includefilter.IncludeTagWritingFilter.getUrl(IncludeTagWritingFilter.java:133)
        at com.cognifide.cq.includefilter.IncludeTagWritingFilter.doFilter(IncludeTagWritingFilter.java:65)
        at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:60)

This occurs when the String url contains a character that should be escaped in URIs because of the usage of the single argument constructor of URI. Please use something like new URI(String, String, String, String) instead of new URI(String)

**Comment by stawniak** [comment]
Good idea.

**Comment by L3444** [comment]
Thank you, the URISyntaxException is fixed in version 2.1.2

The issue of the " character in SSI includes has also been fixed because it gets URI-escaped to %22, but the $ character doesn't. In some, not all, paths that contain $ characters it's an issue because Apache sometimes ignores the $ character. Example:

Original Path: /testsite/test.productid=testvendor=00!$m-i_<>de!$.html
Rendered SSI Include: /testsite/test.productid=testvendor=00!$m-i_%3C%3Ede!$.nocache.html
Apache Request: /testsite/test.productid%3dtestvendor%3d00%21-i_%3c%3ede%21%24
Decoded Apache Request: /testsite/test.productid=testvendor=00!-i_<>de!$

the first $ got lost. This can be fixed by putting a "\" in front of every $ character when rendering the SSI include. (same is true for the " character)

**Comment by stawniak** [comment]
Fix is on its way

**Comment by L3444** [comment]
The $ issue is most likely fixed in e9eefc3a7e48b4127e33c88437e2b940107cded8, thanks. Could you please create a new release?
