### ISSUE TITLE
Links not rewritten when including content for synthetic resources

### ISSUE THREAD

**Issue by mmajchrzak** [Cognifide/Sling-Dynamic-Include#14]
Issue raised through mail support:

When using SDI for synthetic resources, links within the rendered component(s) are not rewritten using the configured sling mappings. They are however rewritten for non-synthetic resources. Can you provide me with an insight on why this might be happening – is this a global issue with SDI? Is there a workaround available that you know off?

So, a concrete example: 

An SDI include of an existing resource
/content/mysite/en_US/home/jcr:content/list.nocache.html
=> when this resource is included through SDI the links from the rendered html are rewritten according to the configured sling:mappings – everything is working superb here

/content/mysite/en_US/home/jcr:content/userMenu.nocache.html/mysite/components/nav/userMenu 
=> when this resource is included through SDI the links from the rendered html are not rewritten according to the configured sling:mappings – I also do not see this item going through the link checker as I do with the previous url.

**Comment by pacoolsky** [comment]
This is most likely related to the changes made in Sling with orderings of filters https://issues.apache.org/jira/browse/SLING-2920

We need to find out solution that it will make it working in both cases, before and after the change.

**Comment by stawniak** [comment]
I can confirm that the reverted filters order that in SP2 is the reason.

In general, the filter order must be < -2500 after 6.0 SP2, and > -2500 before 6.0 SP2.
I made it possible to configure the filter order value in configuration.
Currently, the default is Integer.MIN_VALUE, so the SDI will work with SP2 out of the box.

![sdi-filter-config](https://cloud.githubusercontent.com/assets/13151178/8693743/a8db5054-2ad9-11e5-85c6-2b99944c596c.png)

I've also added SyntheticResourceIncludingServlet class, for experimental approach to including synthetic assets. This approach in not vulnerable to filers order reversed policy.

**Comment by jaspians** [comment]
Hi,

I am facing same issue in AEM 6.1 with SP1. Tried to change the service ranking -2400 and -2600 but in both cases synthetic resources are not being included. Getting error on page- 
Error- [an error occurred while processing this directive]

In logs I see following error- 

unable to include "/content/proj/en/produce/title-of-teaser/placement/level3/_jcr_content/inlineEdit.wkd.nocache.html//apps/proj/components/content/inlineeditingtoolbar" in parsed file C:/Apache22/cache/content/proj/en/produce/title-of-teaser/placement/level3.wkd.html
