### ISSUE TITLE
disallowing nocache selector

### ISSUE THREAD

**Issue by benpeter** [Cognifide/Sling-Dynamic-Include#24]
just wondering: you recommend to disallow the nocache selector in the dispatcher's filter rules.
for me, this disallows the selector for the ssi subrequests as well, effectively making the whole thing disfunctional. 
it there a trick that I don't see?

**Comment by cwoeltge** [comment]
That's for the cache section to remove it from caching.

**Comment by benpeter** [comment]
P|
thanks.
