### ISSUE TITLE
Default configuration Issue on publish

### ISSUE THREAD

**Issue by yagyesh11235** [Cognifide/Sling-Dynamic-Include#7]
I have started working on this module recently facing issue on publisher , after installing the bundle.
The component userinfo and carosuel are not displayed on publisher environment.

Dispacther screen shot:
![image](https://cloud.githubusercontent.com/assets/3796564/5735051/b62b890a-9be5-11e4-9053-5032d900e761.png)

Publisher screen shot:
![image](https://cloud.githubusercontent.com/assets/3796564/5735053/c9874aac-9be5-11e4-89a8-d796b4310be6.png)

Checked the page source for publisher the ssi tags are coming correctly:
```html
<div class="userinfo"><!--#include virtual="/content/geometrixx/en/_jcr_content/userinfo.nocache.html/foundation/components/userinfo" --></div>
```
carousel:
```html
<div class="parbase carousel list"><!--#include virtual="/content/geometrixx/en/_jcr_content/carousel.nocache.html" --></div>

```

Dispatcher.log  for en page 
```
 [Wed Jan 14 11:58:16 2015] [I] [8528(796)] "GET /content/geometrixx/en.html"  200> + 696ms
[Wed Jan 14 11:58:16 2015] [I] [8528(796)] "GET /content/geometrixx/en/_jcr_content/userinfo.nocache.html/foundation/components/userinfo" 200 1838 19ms
[Wed Jan 14 11:58:16 2015] [I] [8528(796)] "GET /content/geometrixx/en/_jcr_content/carousel.nocache.html" 200 4507 36ms
[Wed Jan 14 11:58:16 2015] [I] [8528(844)] "GET /content/geometrixx/en.topnav.1421209651186.html" 200 + 154ms
```

**Comment by trekawek** [comment]
The purpose of the SDI is to replace configured components with SSI include tags that should be evaluated by the Apache. If I understand correctly, this is exactly what happens here - you can see the SSI includes on the publish instance without dispatcher (second screen) and they are evaluated by the Apache (first screen). What is the issue here?

**Comment by yagyesh11235** [comment]
Thanks @trekawek  for the quick response .
The issue is on publisher instance i  see the carousel and userinfo blank.
How can we solve that?

**Comment by yagyesh11235** [comment]
![image](https://cloud.githubusercontent.com/assets/3796564/5736839/94777542-9c00-11e4-808c-4dee5da596d0.png)
 this is the configuration i am using currently

**Comment by trekawek** [comment]
I see it may be little inconvenient to have the component replaced even when hitting the "raw" CQ with no dispatcher. I implemented an improvement - SDI will work only for requests with following header set:

    Server-Agent: Communique-Dispatcher

As a result, SDI will work for dispatche requests, but if you hit the CQ instance directly, it won't replace any components. The header name and value can be configured. The whole option can be disabled by setting the empty string to the *Required header* parameter.

**Comment by yagyesh11235** [comment]
Thanks @trekawek  the fixes works
